"""initial schema

Revision ID: 2fbf6a4c1b91
Revises: 
Create Date: 2026-10-08 18:14:01.221731

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2fbf6a4c1b91'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('size_band', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('joined_on', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('sme_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('institution_name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=48), nullable=False),
    sa.Column('masked_account', sa.String(length=48), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('consent_id', sa.String(length=96), nullable=True),
    sa.Column('consent_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sme_id'], ['smes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_sme_id'), 'accounts', ['sme_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('sme_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sme_id'], ['smes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_sme_id'), 'consents', ['sme_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sme_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=96), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sme_id'], ['smes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index('ix_transactions_sme_date', 'transactions', ['sme_id', 'date'], unique=False)
    op.create_index(op.f('ix_transactions_sme_id'), 'transactions', ['sme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_sme_id'), table_name='transactions')
    op.drop_index('ix_transactions_sme_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_consents_sme_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_accounts_sme_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('smes')
    # ### end Alembic commands ###
