"""loan applications

Revision ID: c3409ffebbc2
Revises: 2fbf6a4c1b91
Create Date: 2026-10-08 22:50:18.562876

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c3409ffebbc2'
down_revision: str | None = '2fbf6a4c1b91'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_applications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sme_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('annual_rate', sa.Float(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recommendation', sa.String(length=48), nullable=True),
    sa.Column('recommendation_note', sa.String(length=400), nullable=True),
    sa.Column('recommendation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['sme_id'], ['smes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applications_sme_id'), 'loan_applications', ['sme_id'], unique=False)
    op.create_index(op.f('ix_loan_applications_status'), 'loan_applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_applications_status'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_sme_id'), table_name='loan_applications')
    op.drop_table('loan_applications')
    # ### end Alembic commands ###
